import org.apache.commons.lang3.builder.ToStringBuilder;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '5/14/15 5:47 PM' with Gradle 2.2.1-20150128190215+0000
 *
 * @author ltudor, @date 5/14/15 5:47 PM
 */
public class SimpleBean {
    private String propertyString;

    private int propertyInt;

    public SimpleBean() {
    }

    public SimpleBean(String propertyString, int propertyInt) {
        this.propertyString = propertyString;
        this.propertyInt = propertyInt;
    }

    public String getPropertyString() {
        return propertyString;
    }

    public void setPropertyString(String propertyString) {
        this.propertyString = propertyString;
    }

    public int getPropertyInt() {
        return propertyInt;
    }

    public void setPropertyInt(int propertyInt) {
        this.propertyInt = propertyInt;
    }

    public boolean someLibraryMethod() {
        return true;
    }

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this);
    }
}
