import org.junit.Test;

import static org.junit.Assert.assertTrue;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ltudor' at '5/14/15 5:47 PM' with Gradle 2.2.1-20150128190215+0000
 *
 * @author ltudor, @date 5/14/15 5:47 PM
 */
public class SimpleBeanTest {
    @Test
    public void testSomeLibraryMethod() {
        SimpleBean classUnderTest = new SimpleBean();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
